name: Matrix Workflow
on: push
jobs:
    build:
        strategy:
            matrix:
                os-version: [ubuntu-latest, windows-latest]
                node-version: [12, 13, 14]
                include:
                    - os-version: ubuntu-latest
                      node-version: 15
                exclude: 
                    - os-version: ubuntu-latest
                      node-version: 12
        runs-on: ${{matrix.os-version}}
        steps:
            - name: get code
              uses: actions/checkout@v4
            - name: install nodejs
              uses: actions/setup-node@v4
              with:
                node-version: ${{matrix.node-version}}
            - name: install deps
              run: npm ci
            - name: build project
              run: npm run build